modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/Tamaized/BeatDownStick/issues"
license="MIT License"

[[mods]]
modId="beatdownstick"
version = "${file.jarVersion}"
displayName="Beat Down Stick"
credits=""
authors="Tamaized"
description='''
Adds a Stick called the Beat Down Stick to annihilate your foes, including Creative Mode Players
'''

[[dependencies.beatdownstick]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.143,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beatdownstick]]
modId = "minecraft"
type = "required"
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"